[pytest]
filterwarnings = ignore::DeprecationWarning
addopts = -v --alluredir=reports/allure-results
markers =
    smoke: mark a test as a smoke test
    regression: mark a test as a regression test
    emailalias: mark a test as a emailalias test
    contactalias: mark a test as a contactalias test
    reliability: mark a test as a reliability test
